options gen2

def always_inline_static() {
}
def noinline_static() {
}
def inline_static() {
}
def alt_kw_inline_static() {
}
def gnu_inline_static() {
}
def cold_used_attrs() {
}
def always_inline_nonstatic() {
}
def gnu_inline_nonstatic() {
}
def noinline_nonstatic() {
}
def inline_nonstatic() {
}
def alt_kw_inline_nonstatic() {
}
def gnu_inline_non_canonical_definition_extern() {
}
def inline_extern() {
}
def alt_kw_inline_extern() {
}
def always_inline_extern() {
}
def gnu_inline_extern() {
}
def always_inline_gnu_inline_extern() {
}
def ensure_use() {
    always_inline_static()
    always_inline_nonstatic()
    gnu_inline_nonstatic()
    inline_static()
    alt_kw_inline_static()
    noinline_static()
    inline_nonstatic()
    alt_kw_inline_nonstatic()
    gnu_inline_static()
    inline_extern()
    alt_kw_inline_extern()
    always_inline_extern()
    gnu_inline_extern()
    always_inline_gnu_inline_extern()
    gnu_inline_non_canonical_definition_extern()
    aliased_fn()
}
