options gen2

struct int_pair_s {
    x : int
    y : int
}
struct Aligned8Struct {
    a : int
    b : int64
}
struct S1 {
    c : int8
    s : int
    ll : int64
}
struct S2 {
    c : int8
    s : int
    ll : int64
}
struct S3 {
    c : int8
    s : int
    ll : int64
}
struct S4 {
    c : int8
    s : int
    ll : int64
}
struct S5 {
    c : int8
    s : int
    ll : int64
}
struct S6 {
    c : int8
    s : int
    ll : int64
}
struct S7 {
    c : int8
    s : int
    ll : int64
}
struct S8 {
    c : int8
    s : int
    ll : int64
}
struct S9 {
    c : int8
    s : int
    ll : int64
}
struct S10 {
    c : int8
    s : int
    ll : int64
}
struct S11 {
    c : int8
    s : int
    ll : int64
}
struct S12 {
    c : int8
    s : int
    ll : int64
}
struct S13 {
    c : int8
    s : int
    ll : int64
}
struct S14 {
    c : int8
    s : int
    ll : int64
}
struct S15 {
    c : int8
    s : int
    ll : int64
}
struct S16 {
    c : int8
    s : int
    ll : int64
}
struct S17 {
    c : int8
    s : S7
}
struct S18 {
    c : int8
    s : S8
}
struct S19 {
    c : int8
    s : S9
}
struct S20 {
    c : int8
    s : S10
}
struct S21 {
    c : int8
    s : S11
}
struct S22 {
    c : int8
    s : S12
}
struct S23 {
    c : int8
    s : S13
}
struct S24 {
    c : int8
    s : S14
}
struct S25 {
    c : int8
    s : S15
}
struct S26 {
    c : int8
    s : S16
}
struct S27 {
    c : int8
    s : S7
}
struct S28 {
    c : int8
    s : S8
}
struct S29 {
    c : int8
    s : S9
}
struct S30 {
    c : int8
    s : S10
}
struct S31 {
    c : int8
    s : S11
}
struct S32 {
    c : int8
    s : S12
}
struct S33 {
    c : int8
    s : S13
}
struct S34 {
    c : int8
    s : S14
}
struct S35 {
    c : int8
    s : S15
}
struct S36 {
    c : int8
    s : S16
}
def alignment_of_aligned8_struct() : size_t {
    return 4
}
