options gen2

def c2da_min_int(a : int; b : int) : int {
    if (a < b) {
        return a
    } else {
        return b
    }
}
def c2da_max_int(a : int; b : int) : int {
    if (a > b) {
        return a
    } else {
        return b
    }
}
def c2da_min_uint(a : uint; b : uint) : uint {
    if (a < b) {
        return a
    } else {
        return b
    }
}
def c2da_max_uint(a : uint; b : uint) : uint {
    if (a > b) {
        return a
    } else {
        return b
    }
}
def c2da_min_int64(a : int64; b : int64) : int64 {
    if (a < b) {
        return a
    } else {
        return b
    }
}
def c2da_max_int64(a : int64; b : int64) : int64 {
    if (a > b) {
        return a
    } else {
        return b
    }
}
def c2da_min_uint64(a : uint64; b : uint64) : uint64 {
    if (a < b) {
        return a
    } else {
        return b
    }
}
def c2da_max_uint64(a : uint64; b : uint64) : uint64 {
    if (a > b) {
        return a
    } else {
        return b
    }
}
def c2da_clip_uint(v : int) : uint {
    if (v < 0) {
        return 0x0
    }
    if (v > 255) {
        return 0xff
    }
    return uint(v)
}
def c2da_bool_to_uint(v : bool) : uint {
    if (v) {
        return 0x1
    } else {
        return 0x0
    }
}
def c2da___assert_fail(expr : void?; file : void?; line : uint; func : void?) {
}
[export]
def rotate_left_8(var x : uint8) : uint8 {
    return x >>> uint8(1)
}
[export]
def rotate_left_16(var x_0 : int) : int {
    return x_0 >>> 2
}
[export]
def rotate_left_32(var x_1 : uint) : uint {
    return x_1 >>> uint(3)
}
[export]
def rotate_right_8(var x_2 : uint8) : uint8 {
    return x_2 >>> uint8(1)
}
[export]
def rotate_right_16(var x_3 : int) : int {
    return x_3 >>> 2
}
[export]
def rotate_right_32(var x_4 : uint) : uint {
    return x_4 >>> uint(3)
}
[export] def main() : int {
    return 0
}
