options gen2

def c2da_min_int(a : int; b : int) : int {
    if (a < b) {
        return a
    } else {
        return b
    }
}
def c2da_max_int(a : int; b : int) : int {
    if (a > b) {
        return a
    } else {
        return b
    }
}
def c2da_min_uint(a : uint; b : uint) : uint {
    if (a < b) {
        return a
    } else {
        return b
    }
}
def c2da_max_uint(a : uint; b : uint) : uint {
    if (a > b) {
        return a
    } else {
        return b
    }
}
def c2da_min_int64(a : int64; b : int64) : int64 {
    if (a < b) {
        return a
    } else {
        return b
    }
}
def c2da_max_int64(a : int64; b : int64) : int64 {
    if (a > b) {
        return a
    } else {
        return b
    }
}
def c2da_min_uint64(a : uint64; b : uint64) : uint64 {
    if (a < b) {
        return a
    } else {
        return b
    }
}
def c2da_max_uint64(a : uint64; b : uint64) : uint64 {
    if (a > b) {
        return a
    } else {
        return b
    }
}
def c2da_clip_uint(v : int) : uint {
    if (v < 0) {
        return 0x0
    }
    if (v > 255) {
        return 0xff
    }
    return uint(v)
}
def c2da_bool_to_uint(v : bool) : uint {
    if (v) {
        return 0x1
    } else {
        return 0x0
    }
}
def c2da___assert_fail(expr : void?; file : void?; line : uint; func : void?) {
}
[export]
def main_0() : int {
    var arr : array<int> = []
    var p : int? = null
    var a : int = int(0)
    var b : int = int(0)
    var c : int = int(0)
    unsafe(unsafe(addr(arr[0]))[0]) = 1
    unsafe(unsafe(addr(arr[0]))[1]) = 2
    unsafe(unsafe(addr(arr[0]))[2]) = 3
    p = unsafe(addr(arr[0]))
    a = *p
    p = unsafe(unsafe(reinterpret<int?>(unsafe(p + 1))))
    b = *p
    p = unsafe(unsafe(reinterpret<int?>(unsafe(p + 1))))
    c = *p
    return int(a) + (b + c)
}
[export] def main() : int {
    return 0
}
